import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Phosphor regular, one family for the whole UI. Names map to node_modules assets. */
const ICONS = [
  'link-simple',
  'lock-simple-open',
  'shield-warning',
  'prohibit',
  'wifi-high',
  'user-circle',
  'envelope-simple',
  'phone',
  'chat-teardrop-text',
  'map-pin',
  'text-aa',
  'key',
  'currency-circle-dollar',
  'app-window',
  'calendar-blank',
  'copy-simple',
  'check',
  'arrow-square-out',
  'x',
  'magnifying-glass',
  'qr-code',
  'warning',
];

export async function buildIconModule() {
  const entries = [];
  for (const name of ICONS) {
    const file = resolve(root, 'node_modules/@phosphor-icons/core/assets/regular', `${name}.svg`);
    const svg = await readFile(file, 'utf8');
    const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim();
    entries.push(`  '${name}': ${JSON.stringify(body)},`);
  }

  const source = `// Generated by scripts/icons-module.mjs from @phosphor-icons/core (regular weight).
// Do not edit by hand; run \`npm run icons\` after changing the icon list.

export type IconName =
${ICONS.map((name) => `  | '${name}'`).join('\n')};

const PATHS: Record<IconName, string> = {
${entries.join('\n')}
};

/** Returns an inline SVG sized to the current font, inheriting colour. */
export function icon(name: IconName, size = 16): SVGSVGElement {
  const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
  svg.setAttribute('viewBox', '0 0 256 256');
  svg.setAttribute('width', String(size));
  svg.setAttribute('height', String(size));
  svg.setAttribute('fill', 'currentColor');
  svg.setAttribute('aria-hidden', 'true');
  svg.setAttribute('focusable', 'false');
  svg.innerHTML = PATHS[name];
  return svg;
}
`;

  const out = resolve(root, 'src/lib/icons.ts');
  await writeFile(out, source);
  return out;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  console.log(`icon module written to ${await buildIconModule()}`);
}
